# Generated by Django 3.1.4 on 2021-01-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sobe_users_key_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatarimage',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='sobe_users',
            name='key_answer',
            field=models.CharField(max_length=20),
        ),
    ]
