# Generated by Django 3.1.4 on 2021-01-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210109_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='date_closed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='lots',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='lots',
            name='num_reason_closing',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lots',
            name='category',
            field=models.ManyToManyField(help_text='Enter lot category', to='main.Categories'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='region',
            field=models.ManyToManyField(help_text='Enter lot region', to='main.Regions'),
        ),
    ]
