# Generated by Django 3.1.4 on 2021-01-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210110_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobe_users',
            name='key_answer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
